apiVersion: apps/v1

kind: Deployment

metadata:
  name: spring-boot-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: spring-boot-app

  template:
    metadata:
      labels:
        app: spring-boot-app

    spec:
      containers:
        - name: spring-boot-container
          image: bbiegajlo/micro-experiment:1.0.0
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
  labels:
    app: spring-boot-app
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: spring-boot