apiVersion: apps/v1
kind: Deployment
metadata:
  name: microexperiment-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      project: micro-experiment
  template:
    metadata:
      labels:
        project: micro-experiment
    spec:
      containers:
        - image: bbiegajlo/micro-experiment:1.0.0
          name: micro-experiment-pod
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: micro-experiment-svc
spec:
  type: NodePort
  ports:
    - name: 8080-8080
      port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 31111
  selector:
    project: micro-experiment